### ISSUE TITLE
Parser Unable to leave a container without going through everything

### ISSUE THREAD

**Issue by erichkeane** [01org/tinycbor#1]
I'm attempting to write a parser, and it seems that the cbor_value_leave_container is only allowed when you're at the end of the container.  I would prefer to be able to leave the container at any time, so that I only need to pick up the necessary data in an array or map.

**Comment by thiagomacieira** [comment]
Use cbor_value_advance from the original container iterator to go to the next item. Leave is intended to work only if you reached the end of the container.
