### ISSUE TITLE
cbor_value_get_map_length outputs wrong value

### ISSUE THREAD

**Issue by pmg23** [01org/tinycbor#17]
According to [RFC 7049](http://tools.ietf.org/html/rfc7049#section-2.1), the length field of a definite-length CBOR map denotes the number of _entries_ in the map.

> The map's length follows the rules for byte strings (major type 2), except that the length denotes the number of pairs, not the length in bytes that the map takes up.

However, `cbor_value_get_map_length(const CborValue *value, size_t *length)` outputs the length integer-divided by 2 (see f0791a2a12599c82e9b65f2923eb1cdd6c141e5d/src/cbor.h#L408). Assuming the intention of this function is to return the number of entries, the result is too low by a factor of 2 (modulo rounding).

As a workaround one can get the correct map size by calling the internal function `_cbor_value_extract_int64_helper` directly.

**Comment by thiagomacieira** [comment]
Oops! I must have got confused by the fact that I multiply the size by 2.

**Comment by pmg23** [comment]
Works great - thanks!
