### ISSUE TITLE
Way to pre-calculate required buffer size on encode

### ISSUE THREAD

**Issue by erichkeane** [01org/tinycbor#2]
Currently, tinycbor requires that we set the buffer in advance pre-allocated.  It would be nice if there was a way to pre-calculate the required size (perhaps pass a NULL buffer, have the library keep incrementing pointers as it goes through, then give a way to get that).

Additionally, it would be a nice feature to have a way AFTER we've finished allocating to determine the ACTUAL consumed size.  This would permit a realloc to happen at least.  Pointer-subtraction is currently possible, though a function to get this would also be nice/future proof.

**Comment by thiagomacieira** [comment]
To get the actual used size, subtract your buffer from encoder.ptr. E.g.:

    uint8_t buffer[1024];
    CborEncoder encoder;
    cbor_encoder_init(&encoder, buffer, sizeof(buffer), 0);
    ...
    size_t len = encoder.ptr - buffer;

**Comment by thiagomacieira** [comment]
Should we have a function for this? Similarly, should we have a parser/decoder function that calculates whether you've parsed to the end of your buffer (no bytes left)?

**Comment by erichkeane** [comment]
Parse to the end is easy enough by just doing an advance and checking for is_invalid.

**Comment by thiagomacieira** [comment]
That tells you that it could read one full element without errors. That doesn't tell you whether there's garbage at the end. You need to compare the value.ptr with the end of your buffer to do that.

**Comment by thiagomacieira** [comment]
47a78569c082905572c7a7c12b5ddbc8248b46e0 implements this.
