### ISSUE TITLE
cborparser.c: Compilation warning with ARM GCC and -Os

### ISSUE THREAD

**Issue by colagrosso** [01org/tinycbor#21]
I'm using tinycbor in a ARM project that uses `-Wall -Werror -Os`. Here is a minimal example that shows the warning that I'm getting: 

```
 $ arm-none-eabi-gcc -Wall -Werror -Os -c cborparser.c
cborparser.c: In function 'iterate_string_chunks':
cborparser.c:563:27: error: 'chunkLen' may be used uninitialized in this function [-Werror=maybe-uninitialized]
                 *result = func(buffer + total, ptr, chunkLen);
                           ^
cborparser.c:527:23: error: 'total' may be used uninitialized in this function [-Werror=maybe-uninitialized]
             *result = func(buffer, ptr, total);
                       ^
cc1: all warnings being treated as errors
```

I understand this is totally GCC's fault. [size_t total](https://github.com/01org/tinycbor/blob/master/src/cborparser.c#L516) and [size_t chunkLen](https://github.com/01org/tinycbor/blob/master/src/cborparser.c#L537) are not used if `extract_length()` returns an error. I could suppress the warning, but I would like to just use tinycbor in the rest of my project without making a special case for it. 

I considered just initializing the variables, but in this case I believe it's better to just set the length to 0 in `extract_length()` when there is an error, which shouldn't happen too often and solves my problem. I'll send a patch request in a moment that does that.

**Comment by thiagomacieira** [comment]
Will accept your PR.
