### ISSUE TITLE
Trying to  compile example: a lot of errors, even with C99 compiler

### ISSUE THREAD

**Issue by bialix** [01org/tinycbor#23]
examples/simplereader.c:74:19: warning: implicit declaration of function 'cbor_value_dup_string' is invalid in C99 [-Wimplicit-function-declaration]
            err = cbor_value_dup_string(it, &buf, &n, it);
                  ^
examples/simplereader.c:164:38: warning: passing 'char *' to parameter of type 'const uint8_t *' (aka 'const unsigned char *') converts between pointers to integer types with different sign [-Wpointer-sign]
    CborError err = cbor_parser_init(buf, length, 0, &parser, &it);
                                     ^~~
examples/../src/cbor.h:223:52: note: passing argument to parameter 'buffer' here
CBOR_API CborError cbor_parser_init(const uint8_t *buffer, size_t size, int flags, CborParser *parser, CborValue *it);
                                                   ^
examples/simplereader.c:171:24: error: 'const uint8_t *' (aka 'const unsigned char *') and 'char *' are not pointers to compatible types
                it.ptr - buf, cbor_error_string(err));
                ~~~~~~ ^ ~~~
2 warnings and 1 error generated.

Also, it's not very Visual Studio friendly, if at all. I've been able to compile it under studio with some changes, but then your example is unable to dump data from CBOR.

It starts print "Map[" and then blows with unexpected EOF error.

**Comment by bialix** [comment]
This is simple file your example was unable to print.
[1.zip](https://github.com/01org/tinycbor/files/214546/1.zip)

**Comment by thiagomacieira** [comment]
Thanks, the API changed since I wrote that example. I'm working on it now.
