### ISSUE TITLE
encode_double/encode_float takes a pointer?

### ISSUE THREAD

**Issue by erichkeane** [01org/tinycbor#3]
I noticed the following 2 signatures:
CBOR_API CborError cbor_encode_float(CborEncoder *encoder, const float *value);
CBOR_API CborError cbor_encode_double(CborEncoder *encoder, const double *value);

Why would these take pointers to a float/double rather than the float/double themselves?  This is fairly inconsistent with the implementation of cbor_encode_int.

**Comment by thiagomacieira** [comment]
It's intentional because I don't want to depend on having a floating point unit on the device. The IAMCU ABI (for the Quarks) does not require x87 support, so those functions would fail to compile if the parameters were passed by value instead of by pointer.

I will document the difference.

**Comment by thiagomacieira** [comment]
I'm building GCC now with support for -miamcu to test, but the best would be to have a static inline front-end function in the header and hand over the pointer to the backend. Best of both worlds.

**Comment by thiagomacieira** [comment]
```c
void addfp(CborEncoder *encoder) 
{ 
    cbor_encode_float(encoder, 1); 
    cbor_encode_double(encoder, 1); 
}
```
Compiled using GCC 6 for -m32 -miamcu:
```asm
        movl    $250, %edx
        movl    %eax, %ebx
        subl    $12, %esp
        movl    %esp, %ecx
        movl    $0x3f800000, (%esp)
        call    cbor_encode_floating_point
        leal    4(%esp), %ecx
        movl    %ebx, %eax
        movl    $251, %edx
        movl    $0, 4(%esp)
        movl    $1072693248, 8(%esp)
        call    cbor_encode_floating_point
        addl    $12, %esp
```
