### ISSUE TITLE
All tests made in Makefile.configure fails due to -e option in echo

### ISSUE THREAD

**Issue by ffontaine** [01org/tinycbor#34]
The following commit (https://github.com/01org/tinycbor/commit/d4c9ecb91ff9f4ac73b1c83dfd909edc69cf8351) added the '-e' option to echo in Makefile.configure which tells echo to interpret the backslash escapes. On my environment, this breaks the .config:

make V=1
[...]
if echo -e "extern int open_memstream(); int main() { return open_memstream(); }" | \
    cc -xc  -o /dev/null - ; \
then \
    echo open_memstream-pass := 1 >&9; \
fi
<stdin>:1:1: error: expected identifier or ‘(’ before ‘-’ token
<stdin>: In function ‘main’:
<stdin>:1:53: warning: implicit declaration of function ‘open_memstream’ [-Wimplicit-function-declaration]
[...]

I suggest to remove "-e".

**Comment by thiagomacieira** [comment]
What environment is that? What shell is your /bin/sh?

**Comment by ffontaine** [comment]
I'm using dash in version 0.5.8-2.1ubu on Ubuntu 16.04.1 LTS but you're right if I switch to bash, the Makefile.configure works however I don't think tinycbor should depend on the type of shell.
The issue is that "echo -e" is not POSIX compliant so the solution would be to replace "echo -e" by "printf". printf will work with all shells.

**Comment by thiagomacieira** [comment]
Indeed, I have a colleague who complained about the dependency on bash. The issue was how to get newlines due to the need for #include. Anyway, looks like printf works, so I'll make that change.

**Comment by ffontaine** [comment]
Thanks for the update, could you make a new release such as 0.31 or 0.4 with these updates? With these bug fixes, I will be able to send a patch to integrate tinycbor into buildroot (https://buildroot.org). Moreover, I have a latest question: why does IoTivity includes directly the source files from tinycbor instead of linking with your library?

**Comment by thiagomacieira** [comment]
Will do. Can you confirm that the current master branch works and you need no further changes?

**Comment by ffontaine** [comment]
I confirm that the version 0.3.1 works well with buildroot, it has been integrated in master branch: https://git.buildroot.net/buildroot/commit/?id=67f96915b14a3f316ee1850253fc7ce11982fafb

Concerning IoTivity, I think that it would be great to check if the tinycbor library is available in the system through a simple:
conf = Configure(env)
if conf.CheckLib('tinycbor'):
    env.AppendUnique(LIBS =['tinycbor'])

Moeover, the IoTivity source files should include <tinycbor/cbor.h> instead of "cbor.h" as this is the path you've choosen to install your headers.
The issue is not only with tinycbor but also with all external dependencies such as gtest, hippomocks, cjon, sqlite3, tinydtls, etc ... In my humble opinion, IoTivity should first check if its dependencies are already available in the system before downloading and compiling a new version. This will decrease the binary/library size of IoTivity and ease the management of the different packages (licenses, versions).
