### ISSUE TITLE
libtinycbor.a created as a directory on some buildsystem

### ISSUE THREAD

**Issue by ffontaine** [01org/tinycbor#36]
Thanks for accepting the change on unnamed union.
There is another issue with tinycbor on buildroot. On some architectures, it seems that libtinycbor.a is created as a directory. You can find more information here: https://patchwork.ozlabs.org/patch/652187/. II have not found the issue yet.

There is juste this line which seems at bit strange to me: "test -d $(@D) || $(MKDIR) $(@D)". I don't think this line is needed because src and tools directories are always there but this is harmless.

Did you already have this issue with libtinycbor.a created as a directory?

**Comment by tpetazzoni** [comment]
I just submitted a pull request that fixes this issue.

**Comment by thiagomacieira** [comment]
Thanks, I would never have guessed what the issue was.

**Comment by ffontaine** [comment]
Thanks to both of you, could you make a new release such as 0.32 so we could remove these two patches from buildroot?

**Comment by thiagomacieira** [comment]
No, as the first patch was removed from master. You'll need to wait for the 0.4 release to get it.

**Comment by ffontaine** [comment]
Dear Thiago,

It seems you reapplied the patch on unnamed union to the dev branch and made a new 0.3.2 release which does not include this change (even it is listed in the release note: https://github.com/01org/tinycbor/releases/tag/v0.3.2). Did you have more tests to do to validate this change and publish a new release? 

Best Regards,

Fabrice

**Comment by thiagomacieira** [comment]
The patch will be in the 0.4 release. I can't update too quickly because people need to get rid of their 0.2 depracated API first.
