### ISSUE TITLE
C4244 warnings when building in Visual Studio

### ISSUE THREAD

**Issue by alradmsft** [01org/tinycbor#45]
Hello,

I'm building the lib in Visual Studio with /W4 switch. I'm getting the warnings below. I understand that in your code you do have checks for data loss during those conversions; however, I have to have code building clean in my environment. I can put together a change to disable the warning in those specific places. Please let me know if that's OK.  

X64:
cborparser.c(802): warning C4244: '=': conversion from 'uint64_t' to 'int', possible loss of data
cborparser.c(808): warning C4244: '=': conversion from 'uint64_t' to 'int', possible loss of data

X86:

cbor.h(166): warning C4201: nonstandard extension used: nameless struct/union
cbor.h(364): warning C4244: '=': conversion from 'uint64_t' to 'std::size_t', possible loss of data
cbor.h(419): warning C4244: '=': conversion from 'uint64_t' to 'std::size_t', possible loss of data
cbor.h(431): warning C4244: '=': conversion from 'uint64_t' to 'std::size_t', possible loss of data

**Comment by thiagomacieira** [comment]
The non-standard extension is fixed by 4628a110b736c3c31bd8c577ea1d29400e0c0a53 (which got into the dev branch as ede7f1431ae06c9086f2a83a57bd7832d99280e3). The other issues are easily solved with an explicit cast.

**Comment by thiagomacieira** [comment]
Can you check if 806f0c9 (from https://github.com/thiagomacieira/tinycbor) solves the issue?

**Comment by alradmsft** [comment]
Yes, that change fixes the the warnings above. Thanks! However, I didn't paste one more from last time (sorry).

compilersupport_p.h(213): warning C4244: 'return': conversion from 'int' to 'unsigned short', possible loss of data

**Comment by thiagomacieira** [comment]
Were there no warnings on lines 190-192 of compilersupport_p.h? That assigns from an uint64_t to int, though the integer operations on the RHS clearly limit the width.

**Comment by alradmsft** [comment]
Hmm... they don't. It looks like only single bit shifts trigger the warning, but not when you have two of them chained. I've reduced the problem to the code below. I will check with our compiler team as to why there is a difference. Will get back to you. 

#include <stdio.h>
#include <stdint.h>

int main()
{
	uint64_t v = 123;
	int i = v;
	int j = v >> 1;
	int k = v << 1;
	int m = v >> 63 << 15;
	wprintf(L"i = %d, j = %d, k = %d, m = %d\n", i, j, k, m);
	return 0;
}

main.cpp(7): warning C4244: 'initializing': conversion from 'uint64_t' to 'int', possible loss of data
main.cpp(8): warning C4244: 'initializing': conversion from 'uint64_t' to 'int', possible loss of data
main.cpp(9): warning C4244: 'initializing': conversion from 'uint64_t' to 'int', possible loss of data

**Comment by thiagomacieira** [comment]
I'll apply this patch as it is for now. If the compiler changes and produces new warnings, we'll fix them then.

**Comment by alradmsft** [comment]
By the way, the 806f0c9 (from https://github.com/thiagomacieira/tinycbor) only addressed warnings in cbor.h. There are still warning on these lines (omitting the compilersuport_p.h since it is tracked by different issue now):

cborencoder.c(301) : warning C4244: '=': conversion from 'unsigned int' to 'uint8_t', possible loss of data
cborparser.c(158) : warning C4244: '=': conversion from 'uint64_t' to '::size_t', possible loss of data
cborparser.c(802) : warning C4244: '=': conversion from 'uint64_t' to 'int', possible loss of data
cborparser.c(808) : warning C4244: '=': conversion from 'uint64_t' to 'int', possible loss of data

The second warning only shows up on x86 build of course.

**Comment by thiagomacieira** [comment]
Can you give me an exhaustive list? I'm away from my Windows environment so I can't get them for myself.

**Comment by alradmsft** [comment]
The above is the exhaustive list, minus the issue in compilersupport_p.h. I can put together a pull request with the changes that I've done to get myself unblocked at the meantime. Right now that change is in my local branch.

**Comment by thiagomacieira** [comment]
Please send the PR. That will help to make sure we've caught them all.

**Comment by alradmsft** [comment]
Sent a PR #48
