### ISSUE TITLE
C4244 warning on return from encode_half() in compilersupport_p.h

### ISSUE THREAD

**Issue by alradmsft** [01org/tinycbor#47]
Hello, 

I followed up on the last warning and I'm being told that the behavior is expected because compiler is "smart" to realize that you shift operation would not produce a value that would overflow. Simple repro:

uint64_t v = 123;
int m1 = v >> 31 << 15; //Issues C4244
int m2 = v >> 32 << 15; //doesn't issue C4244 (for any value of "v")

So the warning for the line:

return sign | ((exp + 15) << 10) | mant;

is legit.

**Comment by thiagomacieira** [comment]
Fixed by 9ba4791ad5b85f3229211b1605caa3c868a4d6f9
