### ISSUE TITLE
encoding a 0-length container at the top level can't return an OOM error

### ISSUE THREAD

**Issue by ghorn** [01org/tinycbor#51]
- initialize an encoder with a 0-size buffer
- create a 0-length array container, and then close it

Expected: some function will return an OOM error, extra_bytes_needed == 1 
Actual: no errors are reported, extra_bytes_needed == 1

The workaround is to check extra_bytes_needed instead of relying on the error codes.
`create_container` explicitly ignores OOM errors https://github.com/01org/tinycbor/blob/9ba4791ad5b85f3229211b1605caa3c868a4d6f9/src/cborencoder.c#L469
so I guess there must be a good reason for it.

**Comment by thiagomacieira** [comment]
Indeed, there's an off-by-one error in the unit test, which created a false-positive in this case. After correcting it, I get a proper test failure.

**Comment by thiagomacieira** [comment]
Proposed fix in 863a480,
