### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by ffontaine** [01org/tinycbor#52]
Do you think it's the good time for a new release of tinycbor? I sent a patch to the soletta project to update the CborEncoder structure (https://github.com/solettaproject/soletta/pull/2347) but they would like a new tag release.

**Comment by thiagomacieira** [comment]
I think it's time, indeed. I'll roll up 0.4.

**Comment by thiagomacieira** [comment]
Release candidate: https://github.com/thiagomacieira/tinycbor/releases/tag/v0.4

**Comment by ffontaine** [comment]
Thanks, why did you release it on a fork? Is it a temporary or a permanent move?

**Comment by thiagomacieira** [comment]
That's just for me to test that everything is fine before I make the official release. And since you asked for the release, I'm giving you the link for you to try with your software too.

**Comment by ffontaine** [comment]
This release seems ok. As soon as it is available on 01org, I will update my PR on soletta project.

**Comment by thiagomacieira** [comment]
Released.
