### ISSUE TITLE
Use latest version of cjson

### ISSUE THREAD

**Issue by ffontaine** [01org/tinycbor#55]
It seems that cjson will soon have its first and official new release (https://github.com/DaveGamble/cJSON/issues/41).

cjson has now make or/and cmake files that install the cJSON.h header into the cjson subdirectory (https://github.com/DaveGamble/cJSON/blob/master/CMakeLists.txt). As soon as this version is released, I would suggest to update the include in Makefile.configure and json2cbor.c. Do you agree?

**Comment by thiagomacieira** [comment]
Sounds good, but we'll leave that for 0.5.

**Comment by thiagomacieira** [comment]
Fixed in 8ba8e2030e44ce939547dc9d3821649f6b2fb053
