### ISSUE TITLE
Update version file

### ISSUE THREAD

**Issue by dantler** [01org/tinycbor#56]
If version is 0.4.0, the VERSION file in the root should reflect that.  Currently the 0.4.0 release was tagged while the VERSION file says 0.3.2.

**Comment by thiagomacieira** [comment]
Actually, the version is updated by the release script. I had to fix it to release 0.4 because we had already updated the version number.

**Comment by dantler** [comment]
You're right! v0.4 is OK.   It doesn't matter what is in the master branch?

**Comment by thiagomacieira** [comment]
The way that the "make relase" script works is that it adds 1 to the minor number, so it would create release 0.5. But now that I think about it, it clearly won't work for patch releases. Not only will it not create the right version number, it would also make a mistake when you tried to release 0.5 after 0.4.1 got merged in...

I'll rethink the script. I should probably do it the other way around: update the release number right *after* the release, to be the next release. I'd just specify if the release is major, minor or patch.

**Comment by thiagomacieira** [comment]
Version updated in e248db9. New script to make tags in the #57
